-- ============================================================================
-- SISTEMA DE GERENCIAMENTO PARA CLÍNICA ODONTOLÓGICA
-- Banco de dados: PostgreSQL
--
-- Antes de executar:
-- 1. Crie um banco de dados vazio no PostgreSQL pelo DBeaver.
-- 2. Abra um editor SQL conectado ao banco criado.
-- 3. Execute este script completo.
-- ============================================================================


-- Inicia uma transação para que toda a estrutura seja criada de forma conjunta.
BEGIN;


-- ============================================================================
-- TABELA: clinics
-- Armazena as clínicas cadastradas no sistema.
-- Embora o projeto comece com uma clínica, a estrutura permite várias clínicas.
-- ============================================================================

CREATE TABLE clinics (
    -- Identificador único da clínica.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Nome da clínica.
    name VARCHAR(150) NOT NULL,

    -- CNPJ da clínica, armazenado somente com números.
    cnpj VARCHAR(14) NOT NULL,

    -- Telefone de contato da clínica.
    phone VARCHAR(20),

    -- E-mail de contato da clínica.
    email VARCHAR(255) NOT NULL,

    -- Endereço completo da clínica.
    address TEXT,

    -- Indica se a clínica está ativa no sistema.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Registra a data e a hora em que a clínica foi cadastrada.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização da clínica.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_clinics PRIMARY KEY (id),

    -- Impede o cadastro de duas clínicas com o mesmo CNPJ.
    CONSTRAINT uq_clinics_cnpj UNIQUE (cnpj),

    -- Impede o cadastro de duas clínicas com o mesmo e-mail.
    CONSTRAINT uq_clinics_email UNIQUE (email)
);


-- ============================================================================
-- TABELA: users
-- Armazena os usuários que possuem acesso ao sistema.
-- Os perfis possíveis são administrador, recepcionista e dentista.
-- ============================================================================

CREATE TABLE users (
    -- Identificador único do usuário.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador da clínica à qual o usuário pertence.
    clinic_id INTEGER NOT NULL,

    -- Nome completo do usuário.
    full_name VARCHAR(150) NOT NULL,

    -- E-mail utilizado para acessar o sistema.
    email VARCHAR(255) NOT NULL,

    -- Senha criptografada do usuário.
    password_hash VARCHAR(255) NOT NULL,

    -- CPF do usuário, armazenado somente com números.
    cpf VARCHAR(11) NOT NULL,

    -- Telefone de contato do usuário.
    phone VARCHAR(20),

    -- Perfil de acesso do usuário.
    role VARCHAR(20) NOT NULL,

    -- Indica se o usuário pode acessar o sistema.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Registra a data e a hora em que o usuário foi cadastrado.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização do usuário.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_users PRIMARY KEY (id),

    -- Relaciona o usuário com sua clínica.
    CONSTRAINT fk_users_clinic
        FOREIGN KEY (clinic_id)
        REFERENCES clinics (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Impede o cadastro de dois usuários com o mesmo e-mail.
    CONSTRAINT uq_users_email UNIQUE (email),

    -- Impede o cadastro de dois usuários com o mesmo CPF.
    CONSTRAINT uq_users_cpf UNIQUE (cpf),

    -- Limita os perfis aos tipos definidos para o sistema.
    CONSTRAINT ck_users_role
        CHECK (role IN ('ADMINISTRATOR', 'RECEPTIONIST', 'DENTIST'))
);


-- ============================================================================
-- TABELA: dentists
-- Armazena os dados profissionais exclusivos dos dentistas.
-- Cada dentista obrigatoriamente corresponde a um usuário do sistema.
-- ============================================================================

CREATE TABLE dentists (
    -- Identificador único do perfil profissional.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador do usuário associado ao dentista.
    user_id INTEGER NOT NULL,

    -- Número de inscrição do dentista no CRO.
    cro_number VARCHAR(30) NOT NULL,

    -- Estado no qual o CRO foi registrado.
    cro_state CHAR(2) NOT NULL,

    -- Especialidade profissional do dentista.
    specialty VARCHAR(100),

    -- Registra a data e a hora de criação do perfil profissional.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização do perfil.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_dentists PRIMARY KEY (id),

    -- Relaciona o dentista com seu usuário de acesso.
    CONSTRAINT fk_dentists_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Garante que um usuário possua no máximo um perfil de dentista.
    CONSTRAINT uq_dentists_user UNIQUE (user_id),

    -- Impede a repetição de um CRO dentro do mesmo estado.
    CONSTRAINT uq_dentists_cro UNIQUE (cro_number, cro_state)
);


-- ============================================================================
-- TABELA: patients
-- Armazena os dados pessoais dos pacientes atendidos pela clínica.
-- O paciente não possui acesso ao sistema nesta etapa do projeto.
-- ============================================================================

CREATE TABLE patients (
    -- Identificador único do paciente.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador da clínica à qual o paciente pertence.
    clinic_id INTEGER NOT NULL,

    -- Nome completo do paciente.
    full_name VARCHAR(150) NOT NULL,

    -- CPF do paciente, armazenado somente com números.
    cpf VARCHAR(11) NOT NULL,

    -- Número do prontuário do paciente dentro da clínica.
    medical_record_number VARCHAR(30) NOT NULL,

    -- Data de nascimento do paciente.
    birth_date DATE NOT NULL,

    -- Telefone de contato do paciente.
    phone VARCHAR(20),

    -- E-mail de contato do paciente.
    email VARCHAR(255),

    -- Endereço completo do paciente.
    address TEXT,

    -- Indica se o cadastro do paciente está ativo.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Registra a data e a hora em que o paciente foi cadastrado.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização do paciente.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_patients PRIMARY KEY (id),

    -- Relaciona o paciente com sua clínica.
    CONSTRAINT fk_patients_clinic
        FOREIGN KEY (clinic_id)
        REFERENCES clinics (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Impede que o mesmo CPF seja cadastrado duas vezes na mesma clínica.
    CONSTRAINT uq_patients_clinic_cpf UNIQUE (clinic_id, cpf),

    -- Impede a repetição do número de prontuário dentro da mesma clínica.
    CONSTRAINT uq_patients_clinic_record
        UNIQUE (clinic_id, medical_record_number)
);


-- ============================================================================
-- TABELA: appointments
-- Armazena os agendamentos de consultas entre pacientes e dentistas.
-- ============================================================================

CREATE TABLE appointments (
    -- Identificador único do agendamento.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador da clínica onde ocorrerá o atendimento.
    clinic_id INTEGER NOT NULL,

    -- Identificador do paciente agendado.
    patient_id INTEGER NOT NULL,

    -- Identificador do dentista responsável pelo atendimento.
    dentist_id INTEGER NOT NULL,

    -- Data e horário previstos para o atendimento.
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Situação atual do agendamento.
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',

    -- Observações administrativas ou informações sobre o agendamento.
    notes TEXT,

    -- Duração prevista da consulta, em minutos.
    duration_minutes INTEGER NOT NULL DEFAULT 30,

    -- Registra a data e a hora em que o agendamento foi criado.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização do agendamento.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_appointments PRIMARY KEY (id),

    -- Relaciona o agendamento com a clínica.
    CONSTRAINT fk_appointments_clinic
        FOREIGN KEY (clinic_id)
        REFERENCES clinics (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Relaciona o agendamento com o paciente.
    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Relaciona o agendamento com o dentista.
    CONSTRAINT fk_appointments_dentist
        FOREIGN KEY (dentist_id)
        REFERENCES dentists (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Limita os estados possíveis de um agendamento.
    CONSTRAINT ck_appointments_status
        CHECK (
            status IN (
                'SCHEDULED',
                'CONFIRMED',
                'COMPLETED',
                'CANCELED'
            )
        ),

    -- Garante que a duração informada seja maior que zero.
    CONSTRAINT ck_appointments_duration
        CHECK (duration_minutes > 0)
);


-- ============================================================================
-- TABELA: medical_records
-- Representa o prontuário permanente de cada paciente.
-- Cada paciente pode possuir somente um prontuário.
-- ============================================================================

CREATE TABLE medical_records (
    -- Identificador único do prontuário.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador do paciente proprietário do prontuário.
    patient_id INTEGER NOT NULL,

    -- Data e horário de abertura do prontuário.
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Informações gerais e observações clínicas iniciais do paciente.
    general_notes TEXT,

    -- Registra a data e a hora em que o prontuário foi criado.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização do prontuário.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_medical_records PRIMARY KEY (id),

    -- Relaciona o prontuário com seu paciente.
    CONSTRAINT fk_medical_records_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Garante que cada paciente possua no máximo um prontuário.
    CONSTRAINT uq_medical_records_patient UNIQUE (patient_id)
);


-- ============================================================================
-- TABELA: clinical_evolutions
-- Armazena as evoluções clínicas registradas no prontuário do paciente.
-- Cada evolução é registrada por um dentista e pode estar ligada a uma consulta.
-- ============================================================================

CREATE TABLE clinical_evolutions (
    -- Identificador único da evolução clínica.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador do prontuário que receberá a evolução.
    medical_record_id INTEGER NOT NULL,

    -- Identificador do dentista responsável pelo registro.
    dentist_id INTEGER NOT NULL,

    -- Identificador do agendamento relacionado à evolução.
    -- O campo pode permanecer vazio enquanto não estiver ligado a uma consulta.
    appointment_id INTEGER,

    -- Data e horário do registro da evolução.
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Situação da evolução: rascunho ou finalizada.
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    -- Descrição da condição e da evolução clínica do paciente.
    description TEXT NOT NULL,

    -- Procedimento realizado durante o atendimento.
    procedure_performed TEXT,

    -- Observações adicionais registradas pelo dentista.
    notes TEXT,

    -- Data e horário em que a evolução foi finalizada.
    finalized_at TIMESTAMP WITH TIME ZONE,

    -- Registra a data e a hora em que a evolução foi criada.
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Registra a data e a hora da última atualização da evolução.
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_clinical_evolutions PRIMARY KEY (id),

    -- Relaciona a evolução com o prontuário do paciente.
    CONSTRAINT fk_clinical_evolutions_record
        FOREIGN KEY (medical_record_id)
        REFERENCES medical_records (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Relaciona a evolução com o dentista que realizou o registro.
    CONSTRAINT fk_clinical_evolutions_dentist
        FOREIGN KEY (dentist_id)
        REFERENCES dentists (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Relaciona a evolução com o agendamento correspondente.
    CONSTRAINT fk_clinical_evolutions_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointments (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Garante que um agendamento gere no máximo uma evolução clínica.
    CONSTRAINT uq_clinical_evolutions_appointment UNIQUE (appointment_id),

    -- Limita os estados possíveis de uma evolução clínica.
    CONSTRAINT ck_clinical_evolutions_status
        CHECK (status IN ('DRAFT', 'FINALIZED')),

    -- Garante que uma evolução finalizada possua data de finalização
    -- e que um rascunho ainda não possua essa data.
    CONSTRAINT ck_clinical_evolutions_finalization
        CHECK (
            (status = 'DRAFT' AND finalized_at IS NULL)
            OR
            (status = 'FINALIZED' AND finalized_at IS NOT NULL)
        )
);


-- ============================================================================
-- TABELA: audit_logs
-- Armazena registros das ações realizadas pelos usuários no sistema.
-- Esses dados auxiliam no rastreamento e na auditoria das operações.
-- ============================================================================

CREATE TABLE audit_logs (
    -- Identificador único do registro de auditoria.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Identificador do usuário que realizou a ação.
    user_id INTEGER NOT NULL,

    -- Nome da ação realizada, como CREATE, UPDATE, LOGIN ou DEACTIVATE.
    action VARCHAR(50) NOT NULL,

    -- Recurso afetado pela ação, como PATIENT ou APPOINTMENT.
    resource VARCHAR(100) NOT NULL,

    -- Endereço IP utilizado pelo usuário.
    ip_address VARCHAR(45),

    -- Detalhes adicionais sobre a operação realizada.
    details TEXT,

    -- Data e horário em que a ação ocorreu.
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Define o campo id como chave primária.
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),

    -- Relaciona o registro de auditoria com o usuário responsável.
    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================================
-- ÍNDICES
-- Os índices abaixo melhoram as consultas realizadas pelas chaves estrangeiras
-- e pelos campos usados com frequência em buscas e filtros.
-- ============================================================================

-- Cria um índice para localizar rapidamente os usuários de uma clínica.
CREATE INDEX idx_users_clinic_id
    ON users (clinic_id);

-- Cria um índice para localizar rapidamente os pacientes de uma clínica.
CREATE INDEX idx_patients_clinic_id
    ON patients (clinic_id);

-- Cria um índice para localizar os agendamentos de uma clínica.
CREATE INDEX idx_appointments_clinic_id
    ON appointments (clinic_id);

-- Cria um índice para localizar os agendamentos de um paciente.
CREATE INDEX idx_appointments_patient_id
    ON appointments (patient_id);

-- Cria um índice para localizar a agenda de um dentista por data.
CREATE INDEX idx_appointments_dentist_scheduled_at
    ON appointments (dentist_id, scheduled_at);

-- Cria um índice para localizar as evoluções de um prontuário.
CREATE INDEX idx_clinical_evolutions_medical_record_id
    ON clinical_evolutions (medical_record_id);

-- Cria um índice para localizar as evoluções registradas por um dentista.
CREATE INDEX idx_clinical_evolutions_dentist_id
    ON clinical_evolutions (dentist_id);

-- Cria um índice para localizar os registros de auditoria de um usuário.
CREATE INDEX idx_audit_logs_user_id
    ON audit_logs (user_id);

-- Cria um índice para ordenar e pesquisar os registros de auditoria por data.
CREATE INDEX idx_audit_logs_occurred_at
    ON audit_logs (occurred_at);


-- ============================================================================
-- FUNÇÃO DE ATUALIZAÇÃO AUTOMÁTICA
-- Atualiza o campo updated_at sempre que um registro for modificado.
-- ============================================================================

-- Cria uma função reutilizável para atualizar a data da última modificação.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- GATILHOS DE ATUALIZAÇÃO
-- Cada gatilho executa a função set_updated_at antes de uma atualização.
-- ============================================================================

-- Atualiza automaticamente updated_at na tabela clinics.
CREATE TRIGGER trg_clinics_set_updated_at
BEFORE UPDATE ON clinics
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Atualiza automaticamente updated_at na tabela users.
CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Atualiza automaticamente updated_at na tabela dentists.
CREATE TRIGGER trg_dentists_set_updated_at
BEFORE UPDATE ON dentists
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Atualiza automaticamente updated_at na tabela patients.
CREATE TRIGGER trg_patients_set_updated_at
BEFORE UPDATE ON patients
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Atualiza automaticamente updated_at na tabela appointments.
CREATE TRIGGER trg_appointments_set_updated_at
BEFORE UPDATE ON appointments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Atualiza automaticamente updated_at na tabela medical_records.
CREATE TRIGGER trg_medical_records_set_updated_at
BEFORE UPDATE ON medical_records
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Atualiza automaticamente updated_at na tabela clinical_evolutions.
CREATE TRIGGER trg_clinical_evolutions_set_updated_at
BEFORE UPDATE ON clinical_evolutions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Confirma a transação e salva toda a estrutura criada no banco de dados.
COMMIT;
