import { FormEvent, ReactNode, useMemo, useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, CircleUserRound, FileText, LayoutDashboard, LogOut, Menu, MoreHorizontal, Pencil, Plus, Search, Send, Settings2, Stethoscope, Users } from 'lucide-react'

type Role = 'admin' | 'patient'
type View = 'dashboard' | 'patients' | 'patient-form' | 'users' | 'user-form' | 'agenda' | 'appointment-form' | 'record'
type Patient = { id: number; name: string; cpf: string; phone: string; email: string; birth: string; address: string; record: string }
type Staff = { id: number; name: string; email: string; role: string; tone: 'blue' | 'green' | 'gray'; cpf: string; phone: string }
type Appointment = { id: number; time: string; patient: string; treatment: string; dentist: string; color: string; top: number }

const patientsSeed: Patient[] = [
  ['Maria da Silva','123.456.789-00','(81) 99999-0001','maria.silva@email.com','15/03/1994','Rua Exemplo, 123 — Recife/PE','0001'],
  ['Pedro Almeida','234.567.890-11','(81) 98888-0022','pedro.almeida@email.com','21/07/1988','Av. Boa Viagem, 80 — Recife/PE','0002'],
  ['Ana Souza','345.678.901-22','(81) 97777-0033','ana.souza@email.com','03/11/1991','Rua das Flores, 52 — Recife/PE','0003'],
  ['Lucas Ferreira','456.789.012-33','(81) 96666-0044','lucas.ferreira@email.com','12/09/1985','Rua do Sol, 44 — Recife/PE','0004'],
  ['Juliana Costa','567.890.123-44','(81) 95555-0055','juliana.costa@email.com','28/01/1996','Rua Aurora, 19 — Recife/PE','0005'],
].map(([name,cpf,phone,email,birth,address,record], index) => ({ id: index + 1, name, cpf, phone, email, birth, address, record }))
const teamSeed: Staff[] = [
  { id: 1, name: 'Paulo Sérgio', email: 'paulo@lumina.com', role: 'Administrador', tone: 'blue', cpf: '11111111111', phone: '(81) 90000-0001' },
  { id: 2, name: 'Carla Mendes', email: 'carla@lumina.com', role: 'Dentista', tone: 'green', cpf: '22222222222', phone: '(81) 90000-0002' },
  { id: 3, name: 'Diego Alves', email: 'diego@lumina.com', role: 'Recepcionista', tone: 'gray', cpf: '33333333333', phone: '(81) 90000-0003' },
  { id: 4, name: 'João Vitor', email: 'joao@lumina.com', role: 'Dentista', tone: 'green', cpf: '44444444444', phone: '(81) 90000-0004' },
]
const appointmentsSeed: Appointment[] = [
  { id: 1, time: '08:30', patient: 'Maria da Silva', treatment: 'Avaliação inicial', dentist: 'Dr. João', color: 'sky', top: 0 },
  { id: 2, time: '10:00', patient: 'Pedro Almeida', treatment: 'Limpeza', dentist: 'Dra. Camila', color: 'mint', top: 2 },
  { id: 3, time: '14:30', patient: 'Ana Souza', treatment: 'Retorno clínico', dentist: 'Dr. João', color: 'lilac', top: 6 },
  { id: 4, time: '16:00', patient: 'Lucas Ferreira', treatment: 'Clareamento', dentist: 'Dra. Camila', color: 'sky', top: 8 },
]

export default function App() {
  const [role, setRole] = useState<Role | null>(null); const [view, setView] = useState<View>('dashboard'); const [patients, setPatients] = useState(patientsSeed); const [team, setTeam] = useState(teamSeed); const [appointments, setAppointments] = useState(appointmentsSeed); const [selected, setSelected] = useState(patientsSeed[0]); const [editingPatient, setEditingPatient] = useState<Patient>(); const [editingUser, setEditingUser] = useState<Staff>(); const [toast, setToast] = useState('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800) }
  if (!role) return <Login onLogin={setRole} />
  if (role === 'patient') return <PatientPortal onLogout={() => setRole(null)} onNotify={notify} />
  const openPatient = (patient: Patient) => { setSelected(patient); setView('record') }
  const logout = () => { setRole(null); setView('dashboard') }
  return <div className="app-shell"><Sidebar view={view} onNavigate={setView} onLogout={logout} /><main className="main-content"><div className="mobile-header"><button className="icon-button"><Menu size={22} /></button><Brand compact /></div>
    {view === 'dashboard' && <Dashboard onNavigate={setView} />}
    {view === 'patients' && <Patients patients={patients} onNew={() => { setEditingPatient(undefined); setView('patient-form') }} onOpen={openPatient} onEdit={(patient) => { setEditingPatient(patient); setView('patient-form') }} onDeactivate={(id) => { setPatients((list) => list.filter((patient) => patient.id !== id)); notify('Paciente inativado.') }} />}
    {view === 'patient-form' && <PatientForm initial={editingPatient} onCancel={() => setView('patients')} onSave={(data) => { setPatients((list) => editingPatient ? list.map((patient) => patient.id === editingPatient.id ? { ...patient, ...data } : patient) : [...list, { ...data, id: list.length + 1, record: String(list.length + 1).padStart(4, '0') }]); setView('patients'); notify(editingPatient ? 'Paciente atualizado.' : 'Paciente cadastrado.') }} />}
    {view === 'users' && <UsersPage team={team} onNew={() => { setEditingUser(undefined); setView('user-form') }} onEdit={(user) => { setEditingUser(user); setView('user-form') }} />}
    {view === 'user-form' && <UserForm initial={editingUser} onCancel={() => setView('users')} onSave={(data) => { setTeam((list) => editingUser ? list.map((user) => user.id === editingUser.id ? { ...user, ...data, tone: toneFor(data.role) } : user) : [...list, { ...data, id: list.length + 1, tone: toneFor(data.role) }]); setView('users'); notify(editingUser ? 'Usuário atualizado.' : 'Usuário criado.') }} />}
    {view === 'agenda' && <Agenda appointments={appointments} onNew={() => setView('appointment-form')} />}
    {view === 'appointment-form' && <AppointmentForm patients={patients} onCancel={() => setView('agenda')} onSave={(data) => { setAppointments((list) => [...list, { ...data, id: list.length + 1, color: 'lilac', top: 4 }]); setView('agenda'); notify('Consulta adicionada à agenda.') }} />}
    {view === 'record' && <Record patient={selected} onBack={() => setView('patients')} onAdd={() => notify('Evolução pronta para registro.')} />}
  </main>{toast && <div className="toast"><Check size={18} />{toast}</div>}</div>
}
function toneFor(role: string): Staff['tone'] { return role === 'Dentista' ? 'green' : role === 'Administrador' ? 'blue' : 'gray' }
function Brand({ compact = false }: { compact?: boolean }) { return <div className={`brand ${compact ? 'brand-compact' : ''}`}><strong>Lumina</strong><span>ODONTO</span></div> }
function Sidebar({ view, onNavigate, onLogout }: { view: View; onNavigate: (view: View) => void; onLogout: () => void }) { const items = [{ id: 'dashboard' as View, label: 'Dashboard', icon: LayoutDashboard }, { id: 'patients' as View, label: 'Pacientes', icon: Users }, { id: 'users' as View, label: 'Equipe', icon: CircleUserRound }, { id: 'agenda' as View, label: 'Agenda', icon: CalendarDays }]; return <aside className="sidebar"><Brand /><nav>{items.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${((id === 'patients' && ['patients','patient-form','record'].includes(view)) || (id === 'users' && ['users','user-form'].includes(view)) || (id === 'agenda' && ['agenda','appointment-form'].includes(view)) || id === view) ? 'active' : ''}`} onClick={() => onNavigate(id)}><span className="nav-icon"><Icon size={18} /></span>{label}</button>)}</nav><div className="sidebar-footer"><div className="user-chip"><span className="avatar small">PS</span><span><b>Paulo Sérgio</b><small>Administrador</small></span><ChevronDown size={16} /></div><button className="logout" onClick={onLogout}><LogOut size={17} /> Sair</button></div></aside> }
function PageHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <header className="page-header"><div className="header-row"><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>{action}</div></header> }
function Button({ children, variant = 'primary', onClick, type = 'button' }: { children: ReactNode; variant?: 'primary' | 'secondary' | 'ghost'; onClick?: () => void; type?: 'button' | 'submit' }) { return <button type={type} className={`button ${variant}`} onClick={onClick}>{children}</button> }
function Login({ onLogin }: { onLogin: (role: Role) => void }) { const [mode, setMode] = useState<Role>('admin'); const [email, setEmail] = useState('admin@clinica.demo'); const [password, setPassword] = useState('Admin@123'); return <div className="login-page"><section className="login-visual"><Brand /><div className="visual-orb orb-one" /><div className="visual-orb orb-two" /><div className="visual-copy"><span>GESTÃO ODONTOLÓGICA</span><h1>Cuidado inteligente<br />para cada sorriso.</h1><p>Gestão simples, segura e próxima da sua clínica.</p></div></section><section className="login-panel"><div className="login-card"><div className="login-heading"><span className="mobile-kicker">LUMINA ODONTO</span><h2>{mode === 'admin' ? 'Acesso da clínica' : 'Área do paciente'}</h2><p>{mode === 'admin' ? 'Entre para gerenciar sua clínica.' : 'Acesse seus atendimentos e fale com a recepção.'}</p></div><div className="login-switch"><button className={mode === 'admin' ? 'active' : ''} onClick={() => { setMode('admin'); setEmail('admin@clinica.demo') }}><Stethoscope size={16} /> Clínica</button><button className={mode === 'patient' ? 'active' : ''} onClick={() => { setMode('patient'); setEmail('maria.silva@email.com') }}><CircleUserRound size={16} /> Paciente</button></div><form onSubmit={(event) => { event.preventDefault(); onLogin(mode) }}><label>E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Senha<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><Button type="submit">Entrar <ArrowRight size={18} /></Button></form><small className="login-note">Acesso destinado a usuários autorizados.</small></div></section></div> }
function Dashboard({ onNavigate }: { onNavigate: (view: View) => void }) { return <><PageHeader title="Bom dia, Administrador" subtitle="Sexta-feira, 19 de setembro" /><div className="stats-grid"><Stat title="Consultas hoje" value="12" detail="3 aguardando confirmação" icon={<CalendarDays />} /><Stat title="Total de pacientes" value="248" detail="+ 8 este mês" icon={<Users />} /><Stat title="Prontuários atualizados" value="18" detail="Últimos 7 dias" icon={<FileText />} /></div><div className="dashboard-grid"><section className="panel appointments-panel"><div className="panel-heading"><div><span className="eyebrow">AGENDA DE HOJE</span><h2>Próximos atendimentos</h2></div><button className="text-button" onClick={() => onNavigate('agenda')}>Ver agenda completa <ArrowRight size={16} /></button></div>{appointmentsSeed.map((item) => <div className="appointment-row" key={item.time}><strong className="appointment-time">{item.time}</strong><div><b>{item.patient}</b><span>{item.treatment}</span></div><small>{item.dentist}</small></div>)}</section><section className="panel daily-summary"><span className="eyebrow">VISÃO RÁPIDA</span><h2>Resumo do dia</h2><p>Organize a agenda e mantenha os prontuários atualizados antes de cada atendimento.</p><div className="summary-stat"><strong>08</strong><span>Pacientes confirmados</span></div><div className="summary-stat"><strong>04</strong><span>Prontuários pendentes</span></div><Button variant="secondary" onClick={() => onNavigate('agenda')}>Atualizar agenda</Button></section></div></> }
function Stat({ title, value, detail, icon }: { title: string; value: string; detail: string; icon: ReactNode }) { return <section className="stat-card"><div className="stat-top"><span>{title}</span><span className="stat-icon">{icon}</span></div><strong>{value}</strong><small>{detail}</small></section> }
function Patients({ patients, onNew, onOpen, onEdit, onDeactivate }: { patients: Patient[]; onNew: () => void; onOpen: (patient: Patient) => void; onEdit: (patient: Patient) => void; onDeactivate: (id: number) => void }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => patients.filter((patient) => `${patient.name} ${patient.cpf} ${patient.phone}`.toLowerCase().includes(query.toLowerCase())), [patients, query]); return <><PageHeader title="Pacientes" subtitle="Gerencie os dados e o histórico clínico dos pacientes." action={<Button onClick={onNew}><Plus size={18} /> Novo paciente</Button>} /><div className="toolbar"><label className="search-field"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pesquisar por nome, CPF ou telefone" /></label><span className="result-count">{filtered.length} pacientes ativos</span></div><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Nome</th><th>CPF</th><th>Telefone</th><th>Ações</th></tr></thead><tbody>{filtered.map((patient) => <tr key={patient.id}><td><button className="table-name" onClick={() => onOpen(patient)}>{patient.name}</button><small>Prontuário nº {patient.record}</small></td><td>{patient.cpf}</td><td>{patient.phone}</td><td><div className="table-actions"><button onClick={() => onOpen(patient)}>Ver</button><button onClick={() => onEdit(patient)}><Pencil size={14} /> Editar</button><button className="danger" onClick={() => onDeactivate(patient.id)}>Inativar</button></div></td></tr>)}</tbody></table></div></section></> }
function Fields({ values, update, user = false }: { values: Record<string, string>; update: (key: string, value: string) => void; user?: boolean }) { const fields = [['name','Nome completo','Ex.: Maria da Silva'],['cpf','CPF','000.000.000-00'],['birth','Data de nascimento','DD/MM/AAAA'],['phone','Telefone','(81) 99999-0000'],['email','E-mail','nome@email.com'],['address','Endereço','Rua, número — Cidade/UF']]; return <>{fields.map(([key,label,placeholder]) => <label key={key}>{label}<input value={values[key] ?? ''} onChange={(event) => update(key,event.target.value)} placeholder={placeholder} required={key === 'name' || key === 'cpf'} /></label>)}{user && <><label>Senha de acesso<input type="password" value={values.password ?? ''} onChange={(event) => update('password',event.target.value)} placeholder="Mínimo de 8 caracteres" required /></label><label>Perfil<select value={values.role ?? 'Recepcionista'} onChange={(event) => update('role',event.target.value)}><option>Administrador</option><option>Dentista</option><option>Recepcionista</option></select></label></>}</> }
function PatientForm({ initial, onCancel, onSave }: { initial?: Patient; onCancel: () => void; onSave: (data: Omit<Patient,'id'|'record'>) => void }) { const [form,setForm] = useState<Record<string,string>>(initial ? { name: initial.name, cpf: initial.cpf, phone: initial.phone, email: initial.email, birth: initial.birth, address: initial.address } : {}); const update=(key:string,value:string)=>setForm((current)=>({...current,[key]:value})); return <><button className="back-link" onClick={onCancel}><ArrowLeft size={18}/> Voltar para pacientes</button><PageHeader title={initial ? 'Editar paciente' : 'Cadastrar paciente'} subtitle="Mantenha os dados do paciente sempre atualizados."/><section className="panel form-panel"><div className="section-title"><span className="section-number">01</span><div><h2>Dados pessoais</h2><p>Informações essenciais para identificar e acompanhar o paciente.</p></div></div><form className="form-grid" onSubmit={(event)=>{event.preventDefault();onSave(form as Omit<Patient,'id'|'record'>)}}><Fields values={form} update={update}/><FormActions cancel={onCancel} label={initial ? 'Salvar alterações' : 'Salvar paciente'}/></form></section></> }
function UsersPage({ team, onNew, onEdit }: { team: Staff[]; onNew: () => void; onEdit: (user: Staff) => void }) { return <><PageHeader title="Equipe" subtitle="Gerencie os perfis de acesso dos profissionais da clínica." action={<Button onClick={onNew}><Plus size={18}/> Novo usuário</Button>}/><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Ações</th></tr></thead><tbody>{team.map((user)=><tr key={user.id}><td className="person-cell"><span className="avatar small">{user.name.split(' ').map((word)=>word[0]).slice(0,2).join('')}</span><b>{user.name}</b></td><td>{user.email}</td><td><span className={`role-pill ${user.tone}`}>{user.role}</span></td><td><div className="table-actions"><button onClick={()=>onEdit(user)}><Pencil size={14}/> Editar</button><button className="icon-button"><MoreHorizontal size={18}/></button></div></td></tr>)}</tbody></table></div></section></> }
function UserForm({ initial, onCancel, onSave }: { initial?: Staff; onCancel: () => void; onSave: (data: Omit<Staff,'id'|'tone'>) => void }) { const [form,setForm]=useState<Record<string,string>>(initial ? { name: initial.name, cpf: initial.cpf, phone: initial.phone, email: initial.email, role: initial.role } : {role:'Recepcionista'}); const update=(key:string,value:string)=>setForm((current)=>({...current,[key]:value})); return <><button className="back-link" onClick={onCancel}><ArrowLeft size={18}/> Voltar para equipe</button><PageHeader title={initial ? 'Editar usuário' : 'Novo usuário'} subtitle="Defina os dados e o perfil de acesso do profissional."/><section className="panel form-panel"><div className="section-title"><span className="section-number">02</span><div><h2>Dados de acesso</h2><p>O perfil define quais áreas da clínica esse usuário poderá acessar.</p></div></div><form className="form-grid" onSubmit={(event)=>{event.preventDefault();onSave(form as Omit<Staff,'id'|'tone'>)}}><Fields values={form} update={update} user/><FormActions cancel={onCancel} label={initial ? 'Salvar alterações' : 'Criar usuário'}/></form></section></> }
function FormActions({ cancel, label }: { cancel: () => void; label: string }) { return <div className="form-actions"><Button variant="secondary" onClick={cancel}>Cancelar</Button><Button type="submit"><Check size={18}/> {label}</Button></div> }
function Agenda({ appointments, onNew }: { appointments: Appointment[]; onNew: () => void }) { const hours=Array.from({length:11},(_,index)=>`${String(index+8).padStart(2,'0')}:00`); return <><PageHeader title="Agenda" subtitle="Sexta-feira, 19 de setembro" action={<Button onClick={onNew}><Plus size={18}/> Nova consulta</Button>}/><section className="panel calendar-panel"><div className="calendar-top"><div><span className="eyebrow">SEXTA-FEIRA</span><h2>Hoje, 19 de setembro</h2></div><button className="filter-button">Todos os dentistas <ChevronDown size={16}/></button></div><div className="calendar-grid"><div className="time-column">{hours.map((hour)=><span key={hour}>{hour}</span>)}</div><div className="calendar-track">{hours.map((hour)=><div className="hour-line" key={hour}><span>{hour}</span></div>)}{appointments.map((item)=><button key={item.id} className={`calendar-event ${item.color}`} style={{top:`${item.top*9.09+2}%`}} onClick={onNew}><b>{item.patient}</b><span>{item.time} · {item.treatment}</span><small>{item.dentist}</small></button>)}</div></div></section></> }
function AppointmentForm({ patients, onCancel, onSave }: { patients: Patient[]; onCancel: () => void; onSave: (data: Omit<Appointment,'id'|'color'|'top'>) => void }) { const [form,setForm]=useState({patient:patients[0]?.name ?? '',date:'19/09/2026',time:'11:00',treatment:'',dentist:'Dr. João'}); const update=(key:string,value:string)=>setForm((current)=>({...current,[key]:value})); return <><button className="back-link" onClick={onCancel}><ArrowLeft size={18}/> Voltar para agenda</button><PageHeader title="Nova consulta" subtitle="Agende um atendimento para um paciente da clínica."/><section className="panel form-panel"><div className="section-title"><span className="section-number">03</span><div><h2>Detalhes do atendimento</h2><p>Escolha paciente, profissional e horário da consulta.</p></div></div><form className="form-grid" onSubmit={(event)=>{event.preventDefault();onSave({patient:form.patient,time:form.time,treatment:form.treatment || 'Consulta',dentist:form.dentist})}}><label>Paciente<select value={form.patient} onChange={(event)=>update('patient',event.target.value)}>{patients.map((patient)=><option key={patient.id}>{patient.name}</option>)}</select></label><label>Data<input value={form.date} onChange={(event)=>update('date',event.target.value)}/></label><label>Horário<input type="time" value={form.time} onChange={(event)=>update('time',event.target.value)} required/></label><label>Profissional<select value={form.dentist} onChange={(event)=>update('dentist',event.target.value)}><option>Dr. João</option><option>Dra. Camila</option></select></label><label className="full-field">Tipo de atendimento<input value={form.treatment} onChange={(event)=>update('treatment',event.target.value)} placeholder="Ex.: Avaliação inicial" required/></label><FormActions cancel={onCancel} label="Confirmar consulta"/></form></section></> }
function PatientPortal({ onLogout, onNotify }: { onLogout: () => void; onNotify: (message: string) => void }) { const [message,setMessage]=useState('');const [requested,setRequested]=useState(false);return <div className="patient-portal"><header className="portal-header"><Brand/><div><span>Olá, Maria</span><button onClick={onLogout}><LogOut size={16}/> Sair</button></div></header><main className="portal-content"><PageHeader title="Olá, Maria da Silva" subtitle="Cuide do seu sorriso com a Lumina Odonto."/><div className="portal-grid"><section className="panel request-card"><div className="portal-icon"><CalendarDays/></div><span className="eyebrow">ATENDIMENTO</span><h2>Precisa falar com a clínica?</h2><p>Solicite um horário e nossa equipe entrará em contato para confirmar.</p>{requested?<div className="request-success"><Check size={20}/><b>Solicitação enviada</b><span>A recepção responderá em breve pelo chat.</span></div>:<Button onClick={()=>{setRequested(true);onNotify('Solicitação enviada para a recepção.')}}><Plus size={18}/> Pedir atendimento</Button>}</section><section className="panel chat-card"><div className="panel-heading"><div><span className="eyebrow">SUPORTE</span><h2>Conversa com a recepção</h2></div><span className="online-dot">Online</span></div><div className="chat-messages"><div className="chat-bubble received">Olá, Maria! Como podemos ajudar hoje?<small>Recepção · 09:42</small></div><div className="chat-bubble sent">Gostaria de agendar uma avaliação.</div></div><form className="chat-compose" onSubmit={(event)=>{event.preventDefault();if(message.trim()){onNotify('Mensagem enviada para a recepção.');setMessage('')}}}><input value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="Escreva uma mensagem..."/><button aria-label="Enviar mensagem"><Send size={18}/></button></form></section></div></main></div> }
function Record({ patient, onBack, onAdd }: { patient: Patient; onBack: () => void; onAdd: () => void }) { const initials=patient.name.split(' ').map((word)=>word[0]).slice(0,2).join('');return <><button className="back-link" onClick={onBack}><ArrowLeft size={18}/> Pacientes</button><section className="patient-hero panel"><span className="avatar hero-avatar">{initials}</span><div><span className="eyebrow">PRONTUÁRIO Nº {patient.record}</span><h1>{patient.name}</h1><p>Paciente desde 2024 · {patient.phone} · {patient.email}</p></div><span className="status-pill"><Activity size={15}/> Cadastro ativo</span></section><div className="tabs"><button className="active">Histórico clínico</button><button>Evoluções</button><button>Consultas anteriores</button></div><div className="record-grid"><section className="panel clinical-history"><div className="panel-heading"><div><span className="eyebrow">LINHA DO TEMPO</span><h2>Histórico clínico</h2></div><button className="icon-button"><Settings2 size={18}/></button></div><Timeline/></section><section className="panel current-care"><span className="eyebrow">ATENDIMENTO ATUAL</span><h2>Registrar evolução</h2><p>Registre uma evolução após concluir o atendimento.</p><Button onClick={onAdd}><Plus size={18}/> Adicionar evolução</Button><hr/><span className="eyebrow">PRÓXIMA CONSULTA</span><strong className="next-date">25 set · 10:00</strong><span className="next-doctor">Dra. Camila Mendes</span></section></div></> }
function Timeline() { return <div className="timeline">{[['19 set 2026','Avaliação inicial','Anamnese preenchida e exame clínico realizado.','Dr. João Vitor'],['12 set 2026','Profilaxia','Limpeza dentária sem intercorrências.','Dra. Camila Mendes'],['04 set 2026','Retorno','Paciente relata melhora na sensibilidade.','Dr. João Vitor']].map(([date,title,description,doctor])=><div className="timeline-item" key={title}><span className="timeline-dot"/><div><small>{date}</small><h3>{title}</h3><p>{description}</p></div><span className="timeline-doctor">{doctor}</span></div>)}</div> }
